services:
  - type: web
    name: keja-digital
    env: elixir
    buildCommand: mix local.hex --force && mix local.rebar --force && mix deps.get --only prod && MIX_ENV=prod mix compile && MIX_ENV=prod mix assets.deploy && MIX_ENV=prod mix release
    startCommand: _build/prod/rel/keja_digital/bin/server