import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :keja_digital, KejaDigitalWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: KejaDigital.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Add this at the end of your dev.exs file
config :keja_digital, :mpesa,
  consumer_key: System.get_env("MPESA_CONSUMER_KEY"),
  consumer_secret: System.get_env("MPESA_CONSUMER_SECRET"),
  business_short_code: System.get_env("MPESA_BUSINESS_SHORT_CODE"),
  passkey: System.get_env("MPESA_PASSKEY")

config :keja_digital, KejaDigital.Repo,
  url: System.get_env("postgresql://gordon_ochieng_user:j2Ydc8FusYMVqMfRgbg7WPdTEme9eiB8@dpg-cv4q1c0gph6c7393v0lg-a/gordon_ochieng"),
  pool_size: 10,
  ssl: true
